baseurl: "https://www.runhangshu.com/"
languageCode: "en-us"
title: "Yarui Li| 李盔盔"
theme: "hugo-ivy"
disqusShortname: "https-www-runhangshu-com" 
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩" 
rssLimit: 100

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/cn/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "中文日记"
      url: "/cn/"
      weight: 3

    
  en:
    - name: "About"
      url: "/cn/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "中文日记"
      url: "/cn/"
      weight: 3

  cn:
    - name: "About"
      url: "/cn/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "中文日记"
      url: "/cn/"
      weight: 3


params:
  description: "Personal website of Yarui Li; 李盔盔的个人网站"
  footer: "&copy; [Yarui Li](/) 2021"
  disqusURL: "https://www.runhangshu.com"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/RunhangShu/RunhangWebsite/tree/main/content"
  twitterImage: "/images/logo.jpg"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/profile.jpeg"
      url: "/"
      alt: "Yarui Li"
      tag: ""


  author:
    en: "Yarui Li"
    cn: "李盔盔"
    animation: ""

  lang:
    edit: 
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
